services:

  ntfy:
    image: binwiederhier/ntfy:v2.27.0
    container_name: ntfy
    restart: unless-stopped
    command: serve
    user: "${PUID}:${PGID}"
    environment:
      TZ: ${TZ}
      NTFY_BASE_URL: https://ntfy.home.${DOMAIN}
      NTFY_LISTEN_HTTP: ":8080"
      NTFY_BEHIND_PROXY: "true"
      NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
      NTFY_CACHE_DURATION: "72h"
      NTFY_AUTH_FILE: /var/lib/ntfy/user.db
      NTFY_AUTH_DEFAULT_ACCESS: deny-all
      NTFY_UPSTREAM_BASE_URL: https://ntfy.sh
    volumes:
      - /opt/homelab/appdata/ntfy:/var/lib/ntfy
    ports:
      - "${TS_IP}:8082:8080"
